[package]
name = "helios"
version = "0.0.0"
edition = "2021"

[dependencies]
bevy = "0.13.0"
bevy_egui = { git = "https://github.com/mvlabat/bevy_egui" }
bevy_rapier3d = "0.25.0"
bevy_screen_diagnostics = "0.5.0"
smart-default = "0.7.1"
bitflags = "2.4.2"
