[package]
name = "helios"
version = "0.0.0"
edition = "2021"

[dependencies]
bevy = "0.12"
bevy_console = "0.10.1"
bevy_egui = "0.24.0"
bevy_screen_diagnostics = "0.4.0"
smart-default = "0.7.1"
clap = { version = "4.5.0", features = ["derive"] }